name: manavo
description: ManaVo is a voice lesson app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  just_audio: ^0.9.28
  rxdart: ^0.27.5
  audio_session: ^0.1.10
  flutter_riverpod: ^1.0.4
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  freezed_annotation: ^2.1.0
  flutter_dotenv: ^5.0.2
  go_router: ^4.5.0
  http: ^0.13.5
  json_serializable: ^6.3.2
  collection: ^1.16.0
  audio_service: ^0.18.7
  get_it: ^7.2.0
  duration: ^3.0.12
  connectivity_plus: ^2.3.7
  shared_preferences: ^2.0.15
  package_info: ^2.0.2
  url_launcher: ^6.1.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.10.0
  mp3_info: ^0.2.0

flutter:
  uses-material-design: true

  assets:
    - res/.env.development
    - res/.env.production
    - assets/images/

flutter_native_splash:
  color: '#38b6ff'
  image: assets/images/ManaVo_white.png
  color_dark: '#262626'
  image_dark: assets/images/ManaVo_white.png
  fullscreen: true
  android_12:
    color: '#38b6ff'
    icon_background_color: '#38b6ff'
    image: assets/images/ManaVo_white_Android.png
    icon_background_color_dark: '#262626'
    image_dark: assets/images/ManaVo_white_Android.png

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icons/ManaVo_icon.png"
  adaptive_icon_background: 'assets/icons/ManaVo_background.png'
  adaptive_icon_foreground: 'assets/icons/ManaVo_icon.png'
